export const AppRoutes = {
  BASE_URL: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  ABOUT: "/about-us",
  CATEGORIES: "/categories",
  OTPGMAIL: "/otpgmail",
  OTPMOBILE: "/otpmobile",
  REGISTERSUCCESS: "/registersuccess",
  FORGOTPASSWORD: "/forgotpassword",
  FORGOTPASSWORDOTP: "/forgotpassword-otp",
  RESETPASSWORDSUCCESS: "/resetpasswordsuccess",
  RESETPASSWORDOTP: "/resetpassword",
  VIDEO_ARTICLES: "/video-articles",
  PRIVACY: "/privacy-policy",
  TERMS: "/terms-conditions",
  CONTACT_US: "/contact-us",
  FAQS: "/faqs",
  GET_SUBSCRIPTION: "/get-subscription",
  PROFILE: "/profile",
  NEW_UPDATES: "/new-updates",
  NEW_UPDATES_SHARE: "/new-updates/:id",
  CATEGORY_DETAIL: "/categorydetail/:UID",
  CATEGORYWISELIST: "/categorywiselisting/:id",
  VIDEO_ARTICLES_DETAILED: "/video-articles-detailed/:uuid",
  BOOKMARKEDARTICLES:"/bookmarkedarticlelists",
  NOTIFICATION: "/notification",
  SUCCESSPAGE:"/payment-successpage"
};
